name: Sync 1080p Custom Formats

on:
  push:
    paths:
      - "profiles/2160p Quality.yml"
  workflow_dispatch:

jobs:
  sync-1080p:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # allow pushing changes back
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install yq
        run: sudo apt-get install -y yq

      - name: Extract and filter custom_formats
        run: |
          # Extract custom_formats from 2160p, excluding any with "2160p" in the name
          yq '.custom_formats | map(select(.name | test("2160p") | not))' \
            "profiles/2160p Quality.yml" > tmp_formats.yml || true 

      - name: Replace custom_formats in 1080p
        run: |
          if ! diff -q tmp_formats.yml <(yq '.custom_formats' "profiles/1080p Quality.yml"); then
            yq -i '.custom_formats = load("tmp_formats.yml")' "profiles/1080p Quality.yml"
          else
            echo "No changes to custom_formats, skipping."
          fi
          
      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add "profiles/1080p Quality.yml"
          git diff --cached --quiet || git commit -m "Sync 1080p custom_formats from 2160p (exclude 2160p entries)"
          git push origin HEAD:main
