name: Sync 1080p Custom Formats

on:
  push:
    paths:
      - "profiles/2160p Quality.yml"
  workflow_dispatch:

jobs:
  sync-1080p:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install mikefarah yq v4
        run: |
          YQ_VERSION="v4.44.1"
          sudo wget -qO /usr/local/bin/yq "https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_amd64"
          sudo chmod +x /usr/local/bin/yq
          yq --version

      - name: Extract and filter sections from 2160p
        run: |
          # custom_formats (exclude any entries with "2160p" in the name)
          yq '.custom_formats | map(select(.name | test("2160p") | not))' \
            "profiles/2160p Quality.yml" > tmp_formats.yml

          # custom_formats_radarr (exclude any entries with "2160p" in the name)
          yq '.custom_formats_radarr // [] | map(select(.name | test("2160p") | not))' \
            "profiles/2160p Quality.yml" > tmp_formats_radarr.yml

          # custom_formats_sonarr (exclude any entries with "2160p" in the name)
          yq '.custom_formats_sonarr // [] | map(select(.name | test("2160p") | not))' \
            "profiles/2160p Quality.yml" > tmp_formats_sonarr.yml

          echo "Filtered blocks prepared:"
          echo "--- custom_formats ---"; cat tmp_formats.yml
          echo "--- custom_formats_radarr ---"; cat tmp_formats_radarr.yml
          echo "--- custom_formats_sonarr ---"; cat tmp_formats_sonarr.yml

      - name: Replace sections in 1080p
        run: |
          # Always replace the three sections; git will only commit if content changes
          yq -i '.custom_formats = load("tmp_formats.yml")' "profiles/1080p Quality.yml"
          yq -i '.custom_formats_radarr = load("tmp_formats_radarr.yml")' "profiles/1080p Quality.yml"
          yq -i '.custom_formats_sonarr = load("tmp_formats_sonarr.yml")' "profiles/1080p Quality.yml"

          echo "Updated 1080p sections:"
          echo "--- custom_formats ---"; yq '.custom_formats' "profiles/1080p Quality.yml"
          echo "--- custom_formats_radarr ---"; yq '.custom_formats_radarr' "profiles/1080p Quality.yml"
          echo "--- custom_formats_sonarr ---"; yq '.custom_formats_sonarr' "profiles/1080p Quality.yml"

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add "profiles/1080p Quality.yml"
          git diff --cached --quiet || git commit -m "Sync 1080p custom formats from 2160p (exclude entries containing '2160p')"
          git push origin HEAD:main
